spring:
  application:
    name: cache-forge
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger
  default-flat-param-object: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        cache.simulation.latency: true
      percentiles:
        cache.simulation.latency: 0.5, 0.95, 0.99
  endpoint:
    prometheus:
      enabled: true

simulation:
  progress:
    percent-step: 5    # send every 5% progress
    count-step: 1000   # OR send every 1000 iterations

rate-limiter:
  configs:
    - clientType: DEFAULT
      algorithm: FIXED_WINDOW
      limit: 5
      windowSizeSeconds: 60
    - clientType: PREMIUM
      algorithm: TOKEN_BUCKET
      capacity: 20
      refillRatePerSecond: 2.0